# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codesite', '0002_auto_20160703_0439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default=datetime.datetime(2016, 7, 3, 6, 20, 39, 132350, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(max_length=254),
        ),
    ]
