# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codesite', '0003_auto_20160703_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='mensagem',
            field=models.TextField(default=datetime.datetime(2016, 7, 11, 23, 26, 3, 44522, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
